# Generated by Django 4.2.2 on 2023-07-14 01:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sureh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10, verbose_name='نام')),
                ('slug', models.SlugField(max_length=10, verbose_name='آدرس')),
                ('number', models.IntegerField(default=0, verbose_name='شماره')),
            ],
            options={
                'verbose_name': 'سوره',
                'verbose_name_plural': 'سورهها',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'موضوع',
                'verbose_name_plural': 'موضوعات',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ayeh', models.IntegerField(default=0, verbose_name='آیه')),
                ('text', models.TextField(verbose_name='متن')),
                ('update', models.DateTimeField(default=django.utils.timezone.now, verbose_name='بروزرسانی')),
                ('status', models.CharField(choices=[('D', 'پیشنویس'), ('P', 'منتشرشده')], max_length=1, verbose_name='وضعیت')),
                ('sureh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quran.sureh', verbose_name='سوره')),
                ('topic', models.ManyToManyField(to='Quran.topic', verbose_name='موضوع')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
