# Generated by Django 4.2.2 on 2023-07-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quran', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sureh',
            options={'ordering': ['number'], 'verbose_name': 'سوره', 'verbose_name_plural': 'سوره ها'},
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('D', 'پیش نویس'), ('P', 'منتشر شده')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
