# Generated by Django 4.2.2 on 2023-07-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quran', '0002_alter_sureh_options_alter_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sureh',
            name='discription',
            field=models.TextField(default='', verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='article',
            name='ayeh',
            field=models.IntegerField(verbose_name='آیه'),
        ),
        migrations.AlterField(
            model_name='sureh',
            name='name',
            field=models.CharField(max_length=10, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='sureh',
            name='number',
            field=models.IntegerField(verbose_name='شماره'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=30, verbose_name='نام'),
        ),
    ]
