# Generated by Django 4.2.2 on 2023-08-08 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quran', '0004_alter_sureh_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sureh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='Quran.sureh', verbose_name='سوره'),
        ),
    ]
