# Generated by Django 4.2.2 on 2023-08-28 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Quran', '0005_alter_article_sureh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('U', 'تایید نشده'), ('R', 'رد شده'), ('C', 'تایید شده')], default='U', max_length=1, verbose_name='وضعیت')),
                ('like', models.IntegerField(default=0, verbose_name='لایک')),
                ('dislike', models.IntegerField(default=0, verbose_name='دیسلایک')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Quran.article', verbose_name='مقاله')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Quran.comment', verbose_name='کامنت مادر')),
            ],
        ),
    ]
