# Generated by Django 4.2.2 on 2023-08-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quran', '0007_alter_comment_options_comment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='', verbose_name='متن'),
            preserve_default=False,
        ),
    ]
