# Generated by Django 4.2.2 on 2023-09-12 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quran', '0010_alter_comment_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آی پی')),
            ],
        ),
        migrations.CreateModel(
            name='Visiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quran.article')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quran.ip')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='visit',
            field=models.ManyToManyField(blank=True, related_name='visits', through='Quran.Visiting', to='Quran.ip', verbose_name='بازدید ها'),
        ),
    ]
