# Generated by Django 4.2.2 on 2023-08-15 12:13

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culprit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='اسم')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='فامیلی')),
                ('instagram_id', models.SlugField(blank=True, verbose_name='آیدی اینستاگرام')),
                ('telegram_id', models.SlugField(blank=True, verbose_name='آیدی تلگرام')),
                ('twitter_id', models.SlugField(blank=True, verbose_name='آیدی توییتر')),
                ('rubika_id', models.SlugField(blank=True, verbose_name='آیدی روبیکا')),
                ('face', models.TextField(verbose_name='مشخصات چهره')),
                ('height', models.IntegerField(null=True, verbose_name='قد')),
                ('weight', models.IntegerField(null=True, verbose_name='وزن')),
                ('body', models.TextField(verbose_name='مشخصات بدنی دیگر')),
                ('job', models.CharField(blank=True, max_length=500, verbose_name='شغل')),
                ('address', models.CharField(blank=True, max_length=5000, verbose_name='آدرس')),
                ('video', models.FileField(blank=True, upload_to='video/justice/culprit', verbose_name='ویدیو')),
                ('v_caption', models.TextField(blank=True, verbose_name='توضیحات ویدیو')),
                ('audio', models.FileField(blank=True, upload_to='audio/justice/culprit', verbose_name='صدا')),
                ('a_caption', models.TextField(blank=True, verbose_name='توضیحات صدا')),
                ('picture', models.ImageField(blank=True, upload_to='image/justice/culprit', verbose_name='عکس')),
                ('p_caption', models.TextField(blank=True, verbose_name='توضیحات عکس')),
            ],
            options={
                'verbose_name': 'مجرم',
                'verbose_name_plural': 'مجرمین',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('is_valid', models.BooleanField(default=False, verbose_name='اعتبار سنجی')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField(verbose_name='آدرس')),
                ('law', models.TextField(verbose_name='قانون')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subfields', to='Justice.crime', verbose_name='زمینه')),
            ],
            options={
                'verbose_name': 'جرم',
                'verbose_name_plural': 'جرم ها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgency', models.CharField(choices=[('A', 'آنی: جرم در حال وقوع است'), ('F', 'فوری: جرم بزودی تکرار می شود'), ('Q', 'غیر فوری: جرم انجام شده و شکایت برای احقاق حق است')], max_length=1, verbose_name='فوریت')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان وقوع')),
                ('discription', models.TextField(blank=True, verbose_name='توضیح دلیل شکایت')),
                ('video', models.FileField(blank=True, upload_to='video/justice/complaint', verbose_name='ویدیو')),
                ('v_caption', models.TextField(blank=True, verbose_name='توضیحات ویدیو')),
                ('audio', models.FileField(blank=True, upload_to='audio/justice/complaint', verbose_name='صدا')),
                ('a_caption', models.TextField(blank=True, verbose_name='توضیحات صدا')),
                ('picture', models.ImageField(blank=True, upload_to='image/justice/complaint', verbose_name='عکس')),
                ('p_caption', models.TextField(blank=True, verbose_name='توضیحات عکس')),
                ('filed', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Y', 'رسیدگی شده'), ('I', 'در حال رسیدگی'), ('L', 'در صف رسیدگی'), ('N', 'بررسی نشده')], default='N', max_length=1, verbose_name='وضعیت شکایت')),
                ('complainant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL, verbose_name='شاکی')),
                ('crime', models.ManyToManyField(related_name='complaints', to='Justice.crime', verbose_name='جرم')),
                ('culprit', models.ManyToManyField(related_name='complaints', to='Justice.culprit', verbose_name='مجرم')),
            ],
            options={
                'verbose_name': 'شکایت',
                'verbose_name_plural': 'شکایات',
                'ordering': ['id'],
            },
        ),
    ]
