# Generated by Django 4.2.2 on 2023-07-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Film', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='status',
            field=models.CharField(choices=[('P', 'در حال پخش'), ('B', 'در حال ساخت'), ('E', 'پایان یافته'), ('U', 'نا معلوم')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
