# Generated by Django 4.2.2 on 2023-07-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Film', '0002_alter_serie_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='status',
            field=models.CharField(choices=[('P', 'در حال پخش'), ('B', 'در حال ساخت'), ('E', 'پایان یافته'), ('U', 'نا معلوم')], default='U', max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='episode',
            name='size',
            field=models.IntegerField(default=0, verbose_name='حجم'),
        ),
        migrations.AddField(
            model_name='serie',
            name='first',
            field=models.IntegerField(default=0, verbose_name='اولین انتشار'),
        ),
        migrations.AddField(
            model_name='serie',
            name='last',
            field=models.IntegerField(default=0, verbose_name='آخرین انتشار'),
        ),
    ]
