# Generated by Django 4.2.2 on 2023-07-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Film', '0003_collection_status_episode_size_serie_first_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='antiquity',
        ),
        migrations.RemoveField(
            model_name='company',
            name='founder',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='antiquity',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='founder',
        ),
        migrations.AddField(
            model_name='company',
            name='year',
            field=models.IntegerField(default=0, verbose_name='سال تاسیس'),
        ),
        migrations.AddField(
            model_name='stream',
            name='year',
            field=models.IntegerField(default=0, verbose_name='سال تاسیس'),
        ),
    ]
