# Generated by Django 4.2.2 on 2023-07-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Film', '0004_remove_company_antiquity_remove_company_founder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='company',
            field=models.ManyToManyField(related_name='films', to='Film.company', verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(related_name='films', to='Film.genre', verbose_name='ژانر'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='company',
            field=models.ManyToManyField(related_name='series', to='Film.company', verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='genre',
            field=models.ManyToManyField(related_name='series', to='Film.genre', verbose_name='ژانر'),
        ),
    ]
