# Generated by Django 4.2.2 on 2023-08-05 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Film', '0005_alter_film_company_alter_film_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='Film.company', verbose_name='شرکت مادر'),
        ),
    ]
