# Generated by Django 4.2.2 on 2023-10-10 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Film', '0006_company_mother'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='Film.stream', verbose_name='پخش کننده'),
        ),
    ]
